### ISSUE TITLE
Node and grunt enabled together

### ISSUE THREAD

**Issue by grit96** [itsapi/post-receive#11]
Currently we do not allow node and grunt to be enabled together.
The reason we are doing this is because they both use a `package.json` and if grunt is enabled the `package.json` is not copied to the destination directory.
I don't see a reason why we can't remove `package.json` from the ignore list and allow both grunt and node to be enabled together.

We will need to consider a few things though:
- We should put grunt dependencies in devDependencies and run `npm install` in the processing directory if grunt is enabled (and of course run `grunt`)
- We should then run `npm install --production` in the output directory once the files have been copied to only install the dependencies and not the devDependencies
- We will also have to put in some logic to copy the `package.json` if there is a src directory (because only the contents of the build directory will be copied)

**Comment by olls** [comment]
A better alternative to moving the `package.json` around would be to always copy the entire project to the output and serving the build directory.
