### ISSUE TITLE
Simplify options

### ISSUE THREAD

**Issue by grit96** [itsapi/post-receive#16]
Remove node specific options and rename them to make them easier to understand.

**Comment by olls** [comment]
Suggested replacement options:

- `build_cmd`: `string`, a shell command to be run in repository root at processing stage
- `copy_from`: `string`, copy the contents of this directory to the output directory
- `copy_to`:    `string`, the directory files should be copied to after processing
- `output-cmd`:   `string`, a shell command to be run in output directory after processing
- `ignore`:    `list`,   a list of files and directories in the output directory that should not be overwritten/deleted
- `url`:       `string`, a link to be displayed after processing on the github listener output
- `email`:     `list`,   a list of email addresses to send error messages if the build fails

**Comment by grit96** [comment]
Consistent underscores/dashes (underscores probably better)

**Comment by grit96** [comment]
Wouldn't it make sense to keep some backward compatibility so we don't have to change all the configs?
